apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-backstage-app
  description: Python app that displays time, named python-backstage-app
  # Example for optional annotations
  annotations:
    github.com/project-slug: cdproyect-org/python-backstage-app
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  # Example for optional owner field  
  owner: development
  lifecycle: experimental