site_name: 'python-backstage-app'
site_description: 'Main documentation for the python-backstage-app'
repo_url: https://github.com/cdproyect-org/python-backstage-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core
  # - redirects:
  #     redirect_maps:
  #       'index.md': 'docs/index.md'

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting started: 'docs/index.md'